### ISSUE TITLE
Prevent python traceback if 'name' is missing

### ISSUE THREAD

**Issue by DrDaveD** [fermitools/htvault-config#6]
Currently if 'name' is not in a list, I get this python trace:
```
Traceback (most recent call last):
  File "/usr/libexec/htvault-config/jsontobash.py", line 54, in <module>
    main()
  File "/usr/libexec/htvault-config/jsontobash.py", line 51, in main
    convertbash("", combined)
  File "/usr/libexec/htvault-config/jsontobash.py", line 29, in convertbash
    convertbash(pfx + '_' + checkbashvar(key), data[key])
  File "/usr/libexec/htvault-config/jsontobash.py", line 36, in convertbash
    convertbash(pfx + '_' + checkbashvar(name), item)
  File "/usr/libexec/htvault-config/jsontobash.py", line 29, in convertbash
    convertbash(pfx + '_' + checkbashvar(key), data[key])
  File "/usr/libexec/htvault-config/jsontobash.py", line 32, in convertbash
    convertbash(pfx, ' '.join([item['name'] for item in data]))
  File "/usr/libexec/htvault-config/jsontobash.py", line 32, in <listcomp>
    convertbash(pfx, ' '.join([item['name'] for item in data]))
KeyError: 'name'
Failure converting config.json to config.bash
```

**Comment by DrDaveD** [comment]
Fixed in 1.3
